services:
    api:
        build: .
        command: python -u app.py
        ports:
            - "5050:5050"
        volumes:
            - .:/app
        links:
            - db
    db:
        image: mongo:latest
        hostname: blocker_mongodb
        environment:
            - MONGO_INITDB_DATABASE=blocker_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017
        volumes:
            - data-volume:/data/db
volumes:
  data-volume: